(* @PATH := '\/DALI 647\/Configuration Pages' *)

VISUALISATION visuDALIControlGearIdentify _VISU_TYPES : 1,3
_BG_BMP : ''
_TEXT : 716
_PAINTZOOM : 100

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 136,1,742,387,439,194
_COLORS : 12632256,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,3,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 141,6,737,381,439,193
_COLORS : 15658734,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Locate Short Address',''
_ZOOM : ''
_INPUT : 0
_TEXT : 1,4294967272,400,0,4,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 151,71,727,316,439,193
_COLORS : 14342874,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '',' Current address              New address                        ',''
_ZOOM : ''
_INPUT : 0
_TEXT : 1,4294967275,400,0,5,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 361,321,377,339,366,331
_COLORS : 16744448,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,6,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 546,321,562,337,556,329
_COLORS : 65280,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,7,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 151,36,267,62,209,49
_COLORS : 15658734,0,255,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Module number',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967283,700,0,71,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 271,36,307,62,289,49
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PrgDALIConfig.bModule_753_647',' %s',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 5,4294967283,700,0,74,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 566,319,696,340,631,329
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Selected short address',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967285,400,0,80,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 381,321,502,342,441,331
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Short address available',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967285,400,0,81,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 606,36,687,62,646,49
_COLORS : 15658734,0,255,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Feedback',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967283,700,0,93,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 691,36,727,62,709,49
_COLORS : 15658734,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PrgDALIConfig.IdentifyControlGear.bFeedback',' %s',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967283,700,0,94,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 371,36,512,62,441,49
_COLORS : 16777215,0,65535,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','PrgDALIConfig.IdentifyControlGear.xQueryShortAddress','','PrgDALIConfig.GroupConfig.xQueryShortAddress'
_DSP : '','Read Short Address',''
_ZOOM : ''
_INPUT : 131072
_TEXT : 5,4294967283,700,0,95,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 161,321,177,337,171,326
_COLORS : 33023,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,278,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 181,319,311,340,246,329
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','New short address',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967285,400,0,279,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuDALI_Menue'
NUM_STRINGS_IN_LIST: 0
NUM_STRINGS_IN_LIST: 0
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 0,0,138,387,69,193
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,581,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 601,109,705,135,653,122
_COLORS : 16777215,0,65535,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','PrgDALIConfig.IdentifyControlGear.xReplaceShortAddress','','PrgDALIConfig.IdentifyControlGear.xReplaceShortAddress'
_DSP : '','Replace',''
_ZOOM : ''
_INPUT : 131072
_TEXT : 5,4294967283,700,0,78,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 601,237,705,263,653,250
_COLORS : 16777215,0,65535,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','PrgDALIConfig.IdentifyControlGear.xCentralOff','','PrgDALIConfig.IdentifyControlGear.xCentralOff'
_DSP : '','Central Off',''
_ZOOM : ''
_INPUT : 131072
_TEXT : 5,4294967283,700,0,86,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 601,204,705,230,653,217
_COLORS : 16777215,0,65535,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','PrgDALIConfig.IdentifyControlGear.xCentralOn','','PrgDALIConfig.IdentifyControlGear.xCentralOn'
_DSP : '','Central On',''
_ZOOM : ''
_INPUT : 131072
_TEXT : 5,4294967283,700,0,87,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 601,149,705,175,653,162
_COLORS : 16777215,0,65535,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','PrgDALIConfig.IdentifyControlGear.xIdentification','PrgDALIConfig.IdentifyControlGear.xIdentification',''
_DSP : '','Identification',''
_ZOOM : ''
_INPUT : 65536
_TEXT : 5,4294967283,700,0,575,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
0
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 172,94,193,115,182,104
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,652,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
1
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 197,94,218,115,207,104
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,653,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
2
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 222,94,243,115,232,104
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,654,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
3
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 247,94,268,115,257,104
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,655,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
4
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 272,94,293,115,282,104
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,656,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
5
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 297,94,318,115,307,104
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,657,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
6
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 322,94,343,115,332,104
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,658,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
7
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 347,94,368,115,357,104
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,659,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
8
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 172,119,193,140,182,129
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,660,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
9
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 197,119,218,140,207,129
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,661,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
10
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 222,119,243,140,232,129
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,662,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
11
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 247,119,268,140,257,129
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,663,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
12
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 272,119,293,140,282,129
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,664,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
13
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 297,119,318,140,307,129
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,665,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
14
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 322,119,343,140,332,129
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,666,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
15
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 347,119,368,140,357,129
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,667,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
16
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 172,144,193,165,182,154
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,668,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
17
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 197,144,218,165,207,154
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,669,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
18
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 222,144,243,165,232,154
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,670,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
19
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 247,144,268,165,257,154
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,671,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
20
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 272,144,293,165,282,154
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,672,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
21
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 297,144,318,165,307,154
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,673,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
22
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 322,144,343,165,332,154
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,674,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
23
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 347,144,368,165,357,154
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,675,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
24
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 172,169,193,190,182,179
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,676,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
25
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 197,169,218,190,207,179
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,677,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
26
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 222,169,243,190,232,179
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,678,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
27
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 247,169,268,190,257,179
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,679,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
28
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 272,169,293,190,282,179
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,680,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
29
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 297,169,318,190,307,179
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,681,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
30
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 322,169,343,190,332,179
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,682,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
31
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 347,169,368,190,357,179
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,683,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
32
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 172,194,193,215,182,204
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,684,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
33
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 197,194,218,215,207,204
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,685,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
34
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 222,194,243,215,232,204
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,686,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
35
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 247,194,268,215,257,204
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,687,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
36
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 272,194,293,215,282,204
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,688,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
37
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 297,194,318,215,307,204
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,689,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
38
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 322,194,343,215,332,204
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,690,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
39
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 347,194,368,215,357,204
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,691,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
40
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 172,219,193,240,182,229
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,692,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
41
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 197,219,218,240,207,229
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,693,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
42
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 222,219,243,240,232,229
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,694,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
43
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 247,219,268,240,257,229
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,695,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
44
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 272,219,293,240,282,229
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,696,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
45
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 297,219,318,240,307,229
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,697,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
46
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 322,219,343,240,332,229
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,698,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
47
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 347,219,368,240,357,229
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,699,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
48
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 172,244,193,265,182,254
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,700,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
49
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 197,244,218,265,207,254
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,701,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
50
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 222,244,243,265,232,254
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,702,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
51
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 247,244,268,265,257,254
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,703,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
52
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 272,244,293,265,282,254
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,704,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
53
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 297,244,318,265,307,254
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,705,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
54
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 322,244,343,265,332,254
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,706,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
55
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 347,244,368,265,357,254
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,707,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
56
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 172,269,193,290,182,279
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,708,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
57
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 197,269,218,290,207,279
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,709,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
58
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 222,269,243,290,232,279
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,710,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
59
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 247,269,268,290,257,279
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,711,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
60
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 272,269,293,290,282,279
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,712,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
61
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 297,269,318,290,307,279
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,713,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
62
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 322,269,343,290,332,279
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,714,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuIdentifyCurrentAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
63
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 347,269,368,290,357,279
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,715,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
0
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 389,94,410,115,399,104
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,587,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
1
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 414,94,435,115,424,104
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,588,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
2
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 439,94,460,115,449,104
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,589,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
3
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 464,94,485,115,474,104
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,590,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
4
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 489,94,510,115,499,104
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,591,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
5
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 514,94,535,115,524,104
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,592,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
6
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 539,94,560,115,549,104
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,593,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
7
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 564,94,585,115,574,104
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,594,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
8
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 389,119,410,140,399,129
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,595,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
9
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 414,119,435,140,424,129
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,596,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
10
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 439,119,460,140,449,129
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,597,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
11
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 464,119,485,140,474,129
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,598,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
12
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 489,119,510,140,499,129
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,599,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
13
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 514,119,535,140,524,129
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,600,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
14
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 539,119,560,140,549,129
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,601,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
15
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 564,119,585,140,574,129
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,602,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
16
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 389,144,410,165,399,154
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,603,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
17
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 414,144,435,165,424,154
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,604,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
18
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 439,144,460,165,449,154
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,605,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
19
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 464,144,485,165,474,154
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,606,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
20
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 489,144,510,165,499,154
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,607,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
21
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 514,144,535,165,524,154
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,608,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
22
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 539,144,560,165,549,154
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,609,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
23
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 564,144,585,165,574,154
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,610,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
24
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 389,169,410,190,399,179
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,611,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
25
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 414,169,435,190,424,179
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,612,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
26
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 439,169,460,190,449,179
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,613,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
27
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 464,169,485,190,474,179
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,614,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
28
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 489,169,510,190,499,179
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,615,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
29
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 514,169,535,190,524,179
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,616,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
30
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 539,169,560,190,549,179
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,617,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
31
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 564,169,585,190,574,179
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,618,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
32
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 389,194,410,215,399,204
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,619,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
33
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 414,194,435,215,424,204
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,620,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
34
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 439,194,460,215,449,204
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,621,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
35
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 464,194,485,215,474,204
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,622,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
36
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 489,194,510,215,499,204
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,623,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
37
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 514,194,535,215,524,204
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,624,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
38
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 539,194,560,215,549,204
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,625,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
39
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 564,194,585,215,574,204
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,626,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
40
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 389,219,410,240,399,229
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,627,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
41
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 414,219,435,240,424,229
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,628,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
42
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 439,219,460,240,449,229
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,629,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
43
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 464,219,485,240,474,229
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,630,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
44
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 489,219,510,240,499,229
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,631,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
45
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 514,219,535,240,524,229
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,632,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
46
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 539,219,560,240,549,229
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,633,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
47
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 564,219,585,240,574,229
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,634,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
48
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 389,244,410,265,399,254
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,635,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
49
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 414,244,435,265,424,254
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,636,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
50
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 439,244,460,265,449,254
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,637,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
51
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 464,244,485,265,474,254
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,638,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
52
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 489,244,510,265,499,254
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,639,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
53
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 514,244,535,265,524,254
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,640,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
54
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 539,244,560,265,549,254
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,641,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
55
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 564,244,585,265,574,254
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,642,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
56
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 389,269,410,290,399,279
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,643,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
57
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 414,269,435,290,424,279
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,644,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
58
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 439,269,460,290,449,279
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,645,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
59
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 464,269,485,290,474,279
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,646,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
60
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 489,269,510,290,499,279
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,647,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
61
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 514,269,535,290,524,279
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,648,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
62
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 539,269,560,290,549,279
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,649,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'visuNewShortAddress'
NUM_STRINGS_IN_LIST: 1
Index
NUM_STRINGS_IN_LIST: 1
63
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 564,269,585,290,574,279
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 0,0,2
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,650,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 5,7,736,378,370,192
_COLORS : 16777215,0,16777215,0,16711680
_VARIABLES : '','','','','','','',''
_THRESH : 'PrgDALIConfig.IdentifyControlGear.xReady','','',''
_DSP : '','Please wait!',''
_ZOOM : ''
_INPUT : 0
_TEXT : 2,4294967272,400,0,582,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_VISUGROUP : 0
_POS : 252,126,508,237,380,181
_THRESH : 'PrgDALIConfig.IdentifyControlGear.xNoError','','',''
_VARIABLES : '','','','','','','',''
_INPUT : 0
_DSP : '','',''
_ZOOM : ''
_TEXT : 5,4294967284,400,0,583,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_FRAME : 1,0,0,1
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)
_BG_BMP : ''
_TEXT : 0
_PAINTZOOM : 100

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 0,0,256,111,128,55
_COLORS : 16777215,0,16777215,0,255
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','$R$NAn error has occurred.$R$NPlease confirm!',''
_ZOOM : ''
_INPUT : 0
_TEXT : 1,4294967277,400,0,584,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 75,70,181,101,128,85
_COLORS : 16777215,0,255,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','','PrgDALIConfig.IdentifyControlGear.xQuit'
_DSP : '','Quit',''
_ZOOM : ''
_INPUT : 131072
_TEXT : 5,4294967283,700,0,585,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)
_KEYINFOLIST : 0
_END_VISUGROUP
_KEYINFOLIST : 0
END_VISUALISATION
