(* @PATH := '\/DALI 647\/Private' *)

VISUALISATION visuDALI_DeviceType_Menue _VISU_TYPES : 1,3
_BG_BMP : ''
_TEXT : 27
_PAINTZOOM : 100

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 0,0,136,386,68,193
_COLORS : 12632256,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,0,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 5,5,131,381,68,193
_COLORS : 15658734,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 1,4294967275,400,0,1,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 11,49,122,80,66,64
_COLORS : 12632256,16711680,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','dwDeviceType.2','',''
_DSP : '','Device Type 2','Discharge$R$Nlamps,excluding fluorescent$R$Nlamps.'
_ZOOM : 'DALI_647_DeviceType2_Main'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,15,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 11,12,122,43,66,27
_COLORS : 12632256,16711680,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','dwDeviceType.1','',''
_DSP : '','Device type 1','Self-contained emergency$R$Nlighting.'
_ZOOM : 'DALI_647_DeviceType1_Main'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,16,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 11,86,122,117,66,101
_COLORS : 12632256,16711680,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','dwDeviceType.3','',''
_DSP : '','Device Type 3','Low voltage halogen lamps'
_ZOOM : 'DALI_647_DeviceType3_Main'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,17,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 11,123,122,154,66,138
_COLORS : 12632256,16711680,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','dwDeviceType.4','',''
_DSP : '','Device Type 4','Supply Voltage controller for$R$Nincandescent lamps'
_ZOOM : 'DALI_647_DeviceType4_Main'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,18,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 11,160,122,191,66,175
_COLORS : 12632256,16711680,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','dwDeviceType.5','',''
_DSP : '','Device type 5','Conversion from digital into$R$ND.C. voltage'
_ZOOM : 'DALI_647_DeviceType5_Main'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,19,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 11,197,122,228,66,212
_COLORS : 12632256,16711680,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','dwDeviceType.6','',''
_DSP : '','Device Type 6','LED modules'
_ZOOM : 'DALI_647_DeviceType6_Main'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,20,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 11,233,122,264,66,248
_COLORS : 12632256,16711680,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','dwDeviceType.7','',''
_DSP : '','Device Type 7','Switching function'
_ZOOM : 'DALI_647_DeviceType7_Main'
_INPUT : 262144
_TEXT : 5,4294967284,700,0,21,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 11,270,122,301,66,285
_COLORS : 12632256,16711680,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','dwDeviceType.8','',''
_DSP : '','Device Type 8','Colour control'
_ZOOM : 'DALI_647_DeviceType8_Main'
_INPUT : 262144
_TEXT : 5,4294967284,700,0,24,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 11,307,122,338,66,322
_COLORS : 12632256,16711680,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','dwDeviceType.9','',''
_DSP : '','Device Type 9','Sequencer'
_ZOOM : 'DALI_647_DeviceType9_Main'
_INPUT : 262144
_TEXT : 5,4294967284,700,0,25,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 3
_NOCOLORS : 1,1
_POS : 11,343,122,374,66,358
_COLORS : 12632256,16711680,12632256,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','dwDeviceType.10','',''
_DSP : '','Device Type 10','Optical control'
_ZOOM : 'DALI_647_DeviceType10_Main'
_INPUT : 262144
_TEXT : 5,4294967284,700,0,26,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)
_KEYINFOLIST : 0
END_VISUALISATION
