(* @PATH := '\/DALI 647\/Private' *)

VISUALISATION visuStatus _VISU_TYPES : 1,3
_BG_BMP : ''
_TEXT : 5
_PAINTZOOM : 100

_SIMPLE : 0
_LINEWIDTH : 2
_NOCOLORS : 1,1
_POS : 0,0,31,31,15,15
_COLORS : 12632256,0,65280,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '$$Index$$','%s',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,700,0,2,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : 'PrgDALIConfig.StatusControlGear.adwFillColour[$$Index$$]','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)
_KEYINFOLIST : 0
END_VISUALISATION
