(* @PATH := '\/DALI 647\/Private' *)

VISUALISATION visuOperatingHours _VISU_TYPES : 1,3
_BG_BMP : ''
_TEXT : 6
_PAINTZOOM : 100

_SIMPLE : 0
_LINEWIDTH : 2
_NOCOLORS : 1,1
_POS : 0,0,21,21,10,10
_COLORS : 16777215,0,16711935,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','PrgDALIConfig.axSelect[$$Index$$]','PrgDALIConfig.axSelect[$$Index$$]',''
_DSP : '$$Index$$','%s',''
_ZOOM : ''
_INPUT : 65536
_TEXT : 5,4294967284,700,0,2,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 2
_NOCOLORS : 1,1
_POS : 20,0,66,21,43,10
_COLORS : 14737632,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PrgDALIConfig.arOperatingHours[$$Index$$]','%2.2f',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 5,4294967285,400,0,4,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : 'PrgDALIConfig.OperatingHours.OldFirmware','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)
_KEYINFOLIST : 0
END_VISUALISATION
