(* @PATH := '' *)

VISUALISATION visuFrontPageDALI _VISU_TYPES : 1,1
_BG_BMP : ''
_TEXT : 37
_PAINTZOOM : 100

_REF : 'Addressing'
NUM_STRINGS_IN_LIST: 0
NUM_STRINGS_IN_LIST: 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 178,137,206,164,192,150
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 1,1,0
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,30,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'ECG_settings'
NUM_STRINGS_IN_LIST: 0
NUM_STRINGS_IN_LIST: 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 211,137,239,165,225,151
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 1,1,0
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,31,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'GroupSceneConfiguration'
NUM_STRINGS_IN_LIST: 0
NUM_STRINGS_IN_LIST: 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 214,173,235,196,224,184
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 1,1,0
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,33,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'Group_assignment'
NUM_STRINGS_IN_LIST: 0
NUM_STRINGS_IN_LIST: 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 179,171,198,196,188,183
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 1,1,0
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,32,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'Lamp_status'
NUM_STRINGS_IN_LIST: 0
NUM_STRINGS_IN_LIST: 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 177,200,198,224,187,212
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 1,1,0
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,34,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'Scene_configuration'
NUM_STRINGS_IN_LIST: 0
NUM_STRINGS_IN_LIST: 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 209,200,230,223,219,211
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 1,1,0
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,35,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_REF : 'Sort_short_address'
NUM_STRINGS_IN_LIST: 0
NUM_STRINGS_IN_LIST: 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 236,198,260,218,248,202
_COLORS : 0,16777215,0
_VARIABLES : '','','','','','','',''
_FRAME : 1,1,0
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,36,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 149,8,675,545,412,276
_COLORS : 8421504,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','$R$N',''
_ZOOM : ''
_INPUT : 0
_TEXT : 1,4294967267,700,0,7,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 171,91,652,247,411,169
_COLORS : 14342874,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Configuration',''
_ZOOM : ''
_INPUT : 0
_TEXT : 1,4294967269,700,255,19,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 171,261,652,526,411,393
_COLORS : 14342874,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Selection menu ',''
_ZOOM : ''
_INPUT : 0
_TEXT : 1,4294967269,700,255,20,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 171,28,652,78,411,53
_COLORS : 12632256,0,11599871,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','DALI configuration tool',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967264,700,0,0,0,0,0
_FONT : '@Arial Unicode MS'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 211,316,372,352,291,334
_COLORS : 12632256,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Addressing',''
_ZOOM : 'visuAddressing'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,1,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 211,368,372,404,291,386
_COLORS : 12632256,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Address assignment ',''
_ZOOM : 'visuSort_short_address'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,2,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 451,316,612,352,531,334
_COLORS : 12632256,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Group assignment ',''
_ZOOM : 'visugroup_assignment'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,3,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 451,368,612,404,531,386
_COLORS : 12632256,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Scene configuration ',''
_ZOOM : 'visuScene_configuration'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,4,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 211,420,372,456,291,438
_COLORS : 12632256,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','ECG settings',''
_ZOOM : 'visuECG_settings'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,5,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 451,420,612,456,531,438
_COLORS : 12632256,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Group-scene config.',''
_ZOOM : 'visuGroupSceneConfiguration'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,6,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 306,146,447,182,376,164
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','DALI Line',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967280,700,0,15,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_BUTTON : ''
_POS : 306,195,492,231,399,213
_THRESH : '','','','DALI_Config.SucheKurzadr'
_INPUT : 131072
_DSP : '','Search short address','Clicking the button "Search Short Address" $R$Nwill start the search for available short addresses.'
_ZOOM : ''
_TEXT : 5,4294967283,700,0,18,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0,157
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @BUTTONCOLORS := '_COLORS : 13158600,0,14474460,0,0' *)
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @GRADIENT_AND_FRAME := '_GRADIENT_AND_FRAME: 0,0,0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)
(* @NO_FRAME_AROUND_BITMAP := '_NO_FRAME_AROUND_BITMAP: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 451,146,492,182,471,164
_COLORS : 65280,0,255,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','DALI_Config.keineJobliste','',''
_DSP : 'DALI_Config.Dali_Linie',' %s','Select DALI Line (1 - 5)'
_ZOOM : ''
_INPUT : 1048576
_TEXT : 5,4294967280,700,0,17,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_POLY : 2
_LINEWIDTH : 2
_NOCOLORS : 1,1
_POLYSORT : 1
_POS : 411,413,411,301,411,525
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','',''
_THRESH : '','','',''
_INPUT : 0
_DSP : '','',''
_ZOOM : ''
_TEXT : 5,4294967284,400,0,23,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_POLY : 2
_LINEWIDTH : 2
_NOCOLORS : 1,1
_POLYSORT : 1
_POS : 411,301,171,301,651,301
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','',''
_THRESH : '','','',''
_INPUT : 0
_DSP : '','',''
_ZOOM : ''
_TEXT : 5,4294967284,400,0,24,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_POLY : 2
_LINEWIDTH : 2
_NOCOLORS : 1,1
_POLYSORT : 1
_POS : 411,131,171,131,651,131
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','',''
_THRESH : '','','',''
_INPUT : 0
_DSP : '','',''
_ZOOM : ''
_TEXT : 5,4294967284,400,0,25,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 451,473,613,509,532,491
_COLORS : 12632256,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Lamp status ',''
_ZOOM : 'visuLamp_status'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,27,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 211,471,372,507,291,489
_COLORS : 12632256,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : 'NOT .EmergencyLighting','','',''
_DSP : '','Emergency lighting',''
_ZOOM : 'visuConfigurationEmergencyLighting'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,28,0,0,0
_FONT : 'Arial'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)
_KEYINFOLIST : 0
END_VISUALISATION
